### ISSUE TITLE
Build broken due to failing test

### ISSUE THREAD

**Issue by spaceninja** [cloudfour/core-gulp-tasks#80]
At the moment, builds for this repo are broken due to a failing test. I was able to reproduce this locally by checking out the repo, running `npm i` and then `npm test`, which gives this error:

```
$ npm test

> @cloudfour/gulp-tasks@2.5.0 test /Users/scott/Sites/core-gulp-tasks
> tape test/*.spec.js | tap-spec


  clean task


    ✖ Cleans up files and folders
    ------------------------------
      operator: ok
      expected: true
      actual:   false
      at: <anonymous> (/Users/scott/Sites/core-gulp-tasks/test/clean.spec.js:15:10)
      stack: |-


  copy task

fs.js:115
    throw err;
    ^

Error: ENOENT: no such file or directory, open 'test/dist/favicon.ico'
    at Object.openSync (fs.js:439:3)
    at Object.readFileSync (fs.js:344:35)
    at readFile (/Users/scott/Sites/core-gulp-tasks/test/utils.js:14:13)
    at Object.readResult (/Users/scott/Sites/core-gulp-tasks/test/utils.js:31:12)
    at /Users/scott/Sites/core-gulp-tasks/test/copy.spec.js:11:24
    at ChildProcess.exithandler (child_process.js:301:5)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:962:16)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:251:5)


npm ERR! Test failed.  See above for more details.
```

**Comment by calebeby** [comment]
I can reproduce this using node 11, but not node 10. Until I figure out why this is failing in node 11, I think using node 10 is a fine workaround
